name: Build test
permissions:
  contents: read
  pull-requests: read
on: [pull_request]
jobs:
  build:
    name: build test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Update submodule'
      run: git submodule update --init
    - name: 'Configure module'
      run: ./configure
    - name: 'Build module'
      run: make
