name: Licence-date-verification
on:
  pull_request:
    branches:
      - master
      - v*

env:
  EXTENSIONS: "c h cpp py go sh mk spec service"
  FILES: "configure configure.d/* *Makefile utils/casctl tools/pckgen.d/deb/debian/rules"
jobs:
  verify-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files_ignore: '.github/**'
      - name: List all changed files
        run: |
          files_to_check=(${{ steps.changed-files.outputs.added_files }})
          files_to_check+=(${{ steps.changed-files.outputs.modified_files }})

          for file in ${files_to_check[@]}; do
            for file_in_list in $FILES; do
              if [[ "$file" == $file_in_list ]]; then
                .github/verify_header.sh "$file"
                continue 2
              fi
            done

            extension=${file##*.}
            if [[ "$EXTENSIONS" =~ $extension ]]; then
              .github/verify_header.sh "$file"
            fi
          done
